server:
  port: 0

spring:
  application:
    name: payment-service
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      naming:
        implicit-strategy: "org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl"
        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
  jackson:
    default-property-inclusion: "non_absent"

eureka:
  instance:
    instanceId: "${spring.application.name}:${random.value}"
    preferIpAddress: true
