server:
  port: 0

spring:
  application:
    name: org-service
  h2:
    console:
      enabled: true

eureka:
  instance:
    instanceId: "${spring.application.name}:${random.value}"
    preferIpAddress: true